### ISSUE TITLE
Mining on network drives (SMB) not working anymore

### ISSUE THREAD

**Issue by Halbert83** [JohnnyFFM/blagominer#13]
In my mining config, I have some internal HDDs and some HDDs from a NAS that is connected via SMB.
This mining configuration worked properly on 911, but on the new version, the plots on the network drive are not being recognized.

**Comment by JohnnyFFM** [comment]
Yes, this is a side effect of having implemented BFS... solution 1: mount your network drives to a local directory... solution 2: i can fix the code.

**Comment by Halbert83** [comment]
Thanks, mounting the NAS as a local directory did the trick. Working like a charm now! :)
