### ISSUE TITLE
Make hdd wake up time configurable

### ISSUE THREAD

**Issue by joyrider3774** [JohnnyFFM/blagominer#2]
Hi,

Currently hdd wakeup is set up only after 3 minutes, some of my disks goto sleep before 3 minutes have elapsed or at least it seems so. Maybe make the hardcoded 180 seconds interval for hdd wake up configurable ? (talking about the value here https://github.com/JohnnyFFM/blagominer/blob/0a747c37f005cfc1403bcf0ccade549347004d5d/blagominer/blagominer.cpp#L370)

**Comment by JohnnyFFM** [comment]
Hi, 

It's very doable. However, I have a feeling that the HDD wakeup feature isn't working at all. My WD drives sometimes perform a head park seconds after the wakeup call. blagominer reloads the directory to trigger a wakeup, but I guess this might be cached in memory and is not yielding the desired wakeup call. I have to investigate this, it's on my agenda. Need to stop these head park counters. Will add a config item then. 

Best, 
Johnny

**Comment by JohnnyFFM** [comment]
done in 997. pre-release today.
